import { useEffect, useState } from 'react';
import { operatorAPI, centreAPI } from '../services/api';

export default function Operators() {
  const [items, setItems] = useState([]); const [centres, setCentres] = useState([]); const [search, setSearch] = useState(''); const [centreId, setCentreId] = useState(''); const [error, setError] = useState('');
  const [form, setForm] = useState({ username: '', password: '', centre_id: '' });
  const load = async () => { try { const [ops, cs] = await Promise.all([operatorAPI.list({ search, centre_id: centreId || undefined }), centreAPI.list()]); setItems(ops.data.items); setCentres(cs.data); setError(''); } catch (e) { setError(e.response?.data?.detail || 'Unable to load operators.'); } };
  useEffect(() => { load(); }, []);
  const create = async (e) => { e.preventDefault(); try { await operatorAPI.create({ ...form, centre_id: Number(form.centre_id) }); setForm({ username: '', password: '', centre_id: '' }); load(); } catch (e) { setError(e.response?.data?.detail || 'Unable to create operator.'); } };
  return <div><h2>Operators</h2><div className="card" style={{padding:'1rem',marginBottom:'1rem'}}><form onSubmit={create} style={{display:'flex',gap:'.6rem',flexWrap:'wrap'}}><input placeholder="Username" required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input placeholder="Password" type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select required value={form.centre_id} onChange={e=>setForm({...form,centre_id:e.target.value})}><option value="">Assign centre</option>{centres.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn btn-primary">Create operator</button></form></div>
  <div style={{display:'flex',gap:'.6rem',marginBottom:'1rem'}}><input placeholder="Search operators" value={search} onChange={e=>setSearch(e.target.value)}/><select value={centreId} onChange={e=>setCentreId(e.target.value)}><option value="">All centres</option>{centres.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn btn-secondary" onClick={load}>Apply</button></div>{error&&<p style={{color:'var(--danger-color)'}}>{error}</p>}
  <div className="card" style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr>{['Username','Role','Centre','Status','Created','Last activity','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.map(o=><tr key={o.id}><td>{o.username}</td><td>{o.role}</td><td><select value={o.centre_id||''} onChange={async e=>{await operatorAPI.assignCentre(o.id,Number(e.target.value));load();}}>{centres.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></td><td>{o.is_active?'Active':'Inactive'}</td><td>{new Date(o.created_at).toLocaleDateString()}</td><td>{o.last_login?new Date(o.last_login).toLocaleString():'Never'}</td><td><button className="btn btn-secondary" onClick={async()=>{await operatorAPI.setStatus(o.id,!o.is_active);load();}}>{o.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div></div>;
}
