import { useEffect, useState } from 'react';
import { analyticsAPI, centreAPI } from '../services/api';

const Card=({label,value})=><div className="card" style={{padding:'1.2rem'}}><small style={{color:'var(--text-secondary)'}}>{label}</small><div style={{fontSize:'1.8rem',fontWeight:700}}>{value}</div></div>;

export default function Reports(){
 const role=localStorage.getItem('role'); const assigned=localStorage.getItem('centre_id');
 const [centre,setCentre]=useState(role==='CENTRE_OPERATOR'?assigned:''); const [centres,setCentres]=useState([]); const [data,setData]=useState(null); const [error,setError]=useState('');
 const load=async()=>{try{const r=await analyticsAPI.overview(centre||null);setData(r.data);setError('')}catch(e){setError(e.response?.data?.detail||'Unable to load analytics.')}};
 useEffect(()=>{if(role!=='CENTRE_OPERATOR')centreAPI.list().then(r=>setCentres(r.data));load()},[]);
 return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h2>Reports & Analytics</h2><p style={{color:'var(--text-secondary)'}}>Authoritative metrics calculated by the backend</p></div>{role!=='CENTRE_OPERATOR'&&<select value={centre} onChange={e=>setCentre(e.target.value)}><option value="">All centres</option>{centres.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<button className="btn btn-secondary" onClick={load}>Refresh</button></div>{error&&<p>{error}</p>}{data&&<><h3>Bookings</h3><div className="stat-grid"><Card label="Today" value={data.bookings.today}/><Card label="This week" value={data.bookings.week}/><Card label="This month" value={data.bookings.month}/></div><h3>Queue</h3><div className="stat-grid"><Card label="Waiting" value={data.queue.waiting}/><Card label="Completed" value={data.queue.completed}/><Card label="Average wait" value={`${data.queue.average_wait_minutes} min`}/></div><h3>Procurement</h3><div className="stat-grid"><Card label="Total accepted quantity" value={data.procurement.total_quantity}/><Card label="Completed" value={data.procurement.completed}/><Card label="Pending" value={data.procurement.pending}/></div><h3>Payments</h3><div className="stat-grid"><Card label="Pending" value={data.payments.pending}/><Card label="Processing" value={data.payments.processing}/><Card label="Paid" value={data.payments.paid}/><Card label="Failed" value={data.payments.failed}/><Card label="Total paid" value={`₹${Number(data.payments.total_paid_amount).toLocaleString('en-IN')}`}/></div></>}</div>
}
